submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 300
mem_gb: 32
nodes: 1
gpus_per_node: 1
name: ${hydra.job.name}


_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: null
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: 1
mem_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
setup: null