defaults:
  - _self_
  - posterior_model: nsf_cnn
  - training: basic
  - paths: Synthetic_long3
  - grid: middle
  - override hydra/launcher: gpu_slurm #=basic for local, serial job submission (debugging)

seed: 0
post_name: test
layers_fname: all_layers_test.p
mb_fname: all_mbs_test.p
num_sims_training: -1 #-1 for all
gt_version: v0
selection_method: advanced_noise

hydra:
  job:
    chdir: True
  run:
    dir: ../../out/${paths.shelf}/${paths.exp_path}/sbi_sims/posteriors

  sweep:
    dir: ../../out/${paths.shelf}/${paths.exp_path}/sbi_sims/posteriors
    subdir: ${post_name}/layer_${grid.layer_idx}_seed_${seed}


  output_subdir: .

  sweeper:
    params:
      grid.layer_idx: range(0,4)
      seed: range(1100,1101)



