defaults:
  - _self_
  - iso_hparams: long_profile
  - setup_file: Ekstrom_full
  - random_seed: 0_seed
  - prior: profile_and_transform
  - scheds: two_phases
  - override hydra/launcher: basic #=basic for local, serial job submission (debugging)

hydra:
  job:
    env_set:
      OMP_NUM_THREADS: 1
    chdir: True
  run:
    dir: ../../out/Ekstrom

  sweep:
    dir: ../../out/Ekstrom/exp2
    subdir: layer_sims/${random_seed.seed}

  output_subdir: .


  sweeper:
      params:
        random_seed.seed: range(0,10)